package main

import (
	"flag"
	"fmt"
	"github.com/gin-gonic/gin"
	"github.com/itcloudy/gin-base-framework/common"
	"github.com/itcloudy/gin-base-framework/crons"
	_ "github.com/itcloudy/gin-base-framework/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/itcloudy/gin-base-framework/router"
	"github.com/itcloudy/gin-base-framework/system"
	"go.uber.org/zap"
	"os"
	"path"
)

// @title  gin-base-framework Server api
// @version 2.0
// @description gin-base-framework Server api
// @termsOfService https://github.com/itcloudy
func main() {

	var err error
	fPath, _ := os.Getwd()
	fPath = path.Join(fPath, "conf")
	configPath := flag.String("c", fPath, "config file path")
	flag.Parse()
	err = system.LoadConfigInformation(*configPath)
	if err != nil {
		return
	}
	go crons.Run()

	if common.ServerInfo.Mode == "debug" {
		gin.SetMode(gin.DebugMode)

	} else if common.ServerInfo.Mode == "release" {
		gin.SetMode(gin.ReleaseMode)
	}
	defer common.Logger.Sync()
	//router init
	router := router.InitRouter()
	server := common.ServerInfo
	serverInfo := common.StringsJoin(server.Host, ":", server.Port)
	// restart
	if server.EnableHttps {
		fmt.Println("server start https")
		err := router.RunTLS(serverInfo, server.CertFile, server.KeyFile)
		fmt.Println(err)
		if err != nil {
			common.Logger.Error("server start failed ", zap.Error(err))
		}
	} else {
		fmt.Printf("server start info: %s\n", serverInfo)
		common.Logger.Info("server start info", zap.String("server", serverInfo))
		common.Logger.Sync()
		err := router.Run(serverInfo)
		if err != nil {
			common.Logger.Error("server start failed", zap.Error(err))
		}
	}
}
