package main

import (
	"github.com/hexiaoyun128/gin-base-framework/common"
	_ "github.com/hexiaoyun128/gin-base-framework/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/hexiaoyun128/gin-base-framework/router"
	"github.com/hexiaoyun128/gin-base-framework/system"
	"github.com/gin-gonic/gin"

	"fmt"
	"github.com/hexiaoyun128/gin-base-framework/crons"
	log "github.com/cihub/seelog"
)

// @title  gin-base-framework Server api
// @version 2.0
// @description Dongjing server
// @termsOfService https://github.com/hexiaoyun128

func main() {

	var err error

	err = system.LoadConfigInformation()
	if err != nil {
		return
	}
	go crons.Run()


	gin.SetMode(gin.ReleaseMode)

	//router init
	router := router.InitRouter()
	server := common.ServerInfo
	serverInfo := common.StringsJoin(server.Host, ":", server.Port)
	// restart
	if server.EnableHttps {
		router.RunTLS(serverInfo, server.CertFile, server.KeyFile)
	} else {
		fmt.Printf("server start info: %s\n", serverInfo)
		log.Infof("server start info: %s", serverInfo)
		router.Run(serverInfo)
	}
}
